/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package programa.start.java.capgemini;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);

        System.out.print("Digite a média: ");
        int media = sc.nextInt();

        if (media <= 5) {
            System.out.println("Aluno Reprovado. ");
        } else if (media == 6) {
            System.out.println("Aluno em Recuperação. ");
        } else {
            System.out.println("Aluno Aprovado. ");

        }
    }
}
