/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package programa.start.java.capgemini;

public class App {

    public static void main(String[] args) {
        System.out.println("Hello World!");

        // Comentários em linha: comenta somente a linha

        /*
         * Comentários em bloco: comenta varias linhas em bloco
         */

        /**
         * Comentários de documentação: gera comentario que fará parte da documentação
         * sobre o programa
         */

    }
}
